### ISSUE TITLE
Android client page sorting issue

### ISSUE THREAD

**Issue by Boycottangent** [maforget/ComicRackKeygen#3]
Thank you for keeping updating a community edition. I don't use the ComicRack Desktop version but just want a good comic reader on my android devices. Overall, this app works perfect except for a wired bug that some comics are not sorted correctly and I believed it's caused by the page number using format like `1/2/...10/11` instead of `001/002/.../010/011`.

Would it be possible to release an updated android version with this bug fixed? It seems that you've fixed this issue for desktop version according to the release note.

**Comment by maforget** [comment]
It is impossible to modify the Android client, it's heavily obfuscated. You should use the desktop client to sync the files or at least convert them so the naming is fixed.
